#!/bin/bash
# 注：原为 `#!/usr/bin/env bash`。真机 2026-09-17 实测：chroot 后 `env` 用的是**从安卓继承的
# PATH**（没有 /usr/bin），于是 `/usr/bin/env: 'bash': No such file or directory` → rc=127。
# 现在 start.sh 在 chroot 前显式给了 Linux PATH（根因修复），这里再改成绝对路径做双保险
# （本层是 Ubuntu，/bin/bash 一定在）。
# =============================================================================
# sunsetlinux · runtime/root/entry.sh
#
# 在 rootfs **内部**（真 chroot 之后）运行：/opt/sunsetlinux/entry.sh
# 职责（architecture.md §3.2 / §4 步 10）：
#   1. 准备 /etc/resolv.conf（从 Android 取当前 DNS，多路回退）
#   2. 准备 /etc/hosts、/etc/hostname
#   3. 设置时区（读 Android 的 persist.sys.timezone）
#   4. HOME=/root、DSH_HOME=/root/.dsh；加载 /root/.dsh/env（若存在且 0600）
#   5. exec /opt/sunsetlinux/supervise.sh --port <port>
#
# **不得**使用 NODE_OPTIONS --import 之类注入式补丁（architecture.md §3.2）。
#
# 关键事实：chroot 之后**看不到 Android 的 /system 与 /data**（根被换成 overlay），
# 所以 getprop / ndc / /system/etc/resolv.conf 在这里都不可用。
# 因此 DNS 与时区由 start.sh 在 chroot **之前**抓取，写到 $LINUX_HOME/etc/
# （= 环境内的 /etc/android-*.txt），本脚本只负责读取与落地。
#
# 另外宿主 $LINUX_HOME/run 是 rbind 进环境内 **/run** 的（见 start.sh 的 rbind_host_run），
# 所以环境内写 /run/dsh.url 等于宿主写 $LINUX_HOME/run/dsh.url，App 侧可直接读。
# ★ 注意方向：是"环境内写 /run"，**不是**"环境内写 $LINUX_HOME/run"。
# =============================================================================
set -uo pipefail

SELF_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
LINUX_HOME="${LINUX_HOME:-/data/sunsetlinux}"
# ★ RUN_DIR 必须是**环境内**的 /run —— 本脚本在 chroot 之后运行，根已经换成 overlay：
#   chroot 里的 "$LINUX_HOME/run"（= /data/sunsetlinux/run）既不是宿主那个目录，也不是
#   rbind 进来的 /run，而是可写层（upperdir）上**凭空新建的一个目录**。
#   2026-09-17 真机事故：dsh.pid / dsh.port / dsh.url / linux.log 全落进那个假目录 →
#   宿主侧 linuxctl（= App）读 $LINUX_HOME/run/dsh.url 永远为 null →
#   App 报"环境已在运行，但登录地址还没写出来（run/dsh.url 尚未就绪）"，WebView 打不开。
#   （同一份代码在 1.0.26 及以前就是这样，见 docs/STATUS.md §3.10.31。）
#   SUNSETLINUX_RUN_DIR 只作覆盖口（宿主侧自测 / proot 运行时同款约定），默认 /run。
RUN_DIR="${SUNSETLINUX_RUN_DIR:-/run}"

log() {
    local line
    line="[$(date '+%Y-%m-%d %H:%M:%S')] [entry.sh] $*"
    printf '%s\n' "$line" >&2
    [ -d "$RUN_DIR" ] && printf '%s\n' "$line" >> "$RUN_DIR/linux.log" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# 参数
# ---------------------------------------------------------------------------
PORT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --port) PORT="${2:-}"; shift 2 ;;
        [0-9]*) PORT="$1"; shift ;;
        *) shift ;;
    esac
done
case "${PORT:-}" in ''|*[!0-9]*) PORT=3080 ;; esac
if [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then PORT=3080; fi

# ---------------------------------------------------------------------------
# 1) DNS：多路回退
#    优先级：
#      a) 宿主 start.sh 落下的 /etc/android-resolv.txt（窗口期前就抓好了，最可靠）
#      b) /etc/resolv.conf 里已有的、且能解析的 IPv4（宿主的 ubuntu-base 自带，可能是占位）
#      c) /proc/net/route 默认网关所在网段的常见 DNS（不猜，只做最后兜底）
#      d) 全部失败 → 写 8.8.8.8/1.1.1.1 并**在日志里明确警告**
# ---------------------------------------------------------------------------
collect_dns() {
    local out="" line ns
    # a) 宿主预先抓取的
    if [ -f /etc/android-resolv.txt ]; then
        while IFS= read -r line; do
            ns="$(printf '%s' "$line" | awk '{for(i=1;i<=NF;i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}')"
            [ -n "$ns" ] && out="$out $ns"
        done < /etc/android-resolv.txt
        [ -n "$out" ] && log "DNS 来源：宿主预抓取 /etc/android-resolv.txt"
    fi

    # b) 已有 resolv.conf（跳过本地回环 stub，chroot 里没有 systemd-resolved）
    if [ -z "$out" ] && [ -f /etc/resolv.conf ]; then
        local existing=""
        while IFS= read -r line; do
            ns="$(printf '%s' "$line" | awk '/^[[:space:]]*nameserver/ {print $2; exit}')"
            case "$ns" in
                127.*|::1|"") continue ;;
                *[!0-9.a-fA-F:]*) continue ;;
            esac
            existing="$existing $ns"
        done < /etc/resolv.conf
        if [ -n "$existing" ]; then
            out="$existing"
            log "DNS 来源：rootfs 已有 /etc/resolv.conf"
        fi
    fi

    # c) 宿主 start.sh 留下的 getprop 原始值
    if [ -z "$out" ] && [ -f /etc/android-dns.txt ]; then
        out="$(tr ',;' '  ' < /etc/android-dns.txt | awk '{for(i=1;i<=NF;i++) printf "%s ", $i}')"
        [ -n "$out" ] && log "DNS 来源：/etc/android-dns.txt（宿主 getprop）"
    fi

    # d) 兜底
    if [ -z "$out" ]; then
        out="8.8.8.8 1.1.1.1"
        log "WARN: 无法从 Android 取得 DNS，兜底使用 $out（若域名解析失败请检查宿主 netd 配置）"
    fi
    printf '%s' "$out"
}

DNS_LIST="$(collect_dns)"
{
    printf '# generated by sunsetlinux entry.sh at %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf '# 每次启动都会重建（rootfs 的 /etc/resolv.conf 可能是指向 systemd 的坏软链）\n'
    for ns in $DNS_LIST; do
        printf 'nameserver %s\n' "$ns"
    done
    printf 'options timeout:2 attempts:2\n'
} > /etc/resolv.conf.new 2>/dev/null || log "WARN: 无法写 /etc/resolv.conf.new（只读？）"

# resolv.conf 可能是软链（→/run/systemd/resolve/stub-resolv.conf），先把软链去掉
if [ -f /etc/resolv.conf.new ]; then
    if [ -L /etc/resolv.conf ]; then rm -f /etc/resolv.conf 2>/dev/null || true; fi
    if mv -f /etc/resolv.conf.new /etc/resolv.conf 2>/dev/null; then
        log "已写 /etc/resolv.conf：$(printf '%s' "$DNS_LIST" | tr '\n' ' ')"
    else
        log "WARN: 替换 /etc/resolv.conf 失败"
    fi
fi

# ---------------------------------------------------------------------------
# 2) /etc/hosts 与 /etc/hostname
# ---------------------------------------------------------------------------
if [ ! -s /etc/hosts ] || ! grep -q '^127\.0\.0\.1' /etc/hosts 2>/dev/null; then
    {
        printf '127.0.0.1\tlocalhost\n'
        printf '::1\t\tlocalhost ip6-localhost ip6-loopback\n'
        printf '127.0.0.1\tsunsetlinux\n'
        printf 'fe00::0\t\tip6-localnet\n'
        printf 'ff00::0\t\tip6-mcastprefix\n'
        printf 'ff02::1\t\tip6-allnodes\n'
        printf 'ff02::2\t\tip6-allrouters\n'
    } > /etc/hosts 2>/dev/null && log "已写 /etc/hosts"
fi
printf 'sunsetlinux\n' > /etc/hostname 2>/dev/null || true

# ---------------------------------------------------------------------------
# 3) 时区：优先宿主预抓取的 /etc/android-timezone.txt（getprop persist.sys.timezone）
#    回退 /etc/timezone（base 层由 tzdata 生成），最后固定 UTC。
# ---------------------------------------------------------------------------
TZ_NAME=""
if [ -f /etc/android-timezone.txt ]; then
    TZ_NAME="$(head -n1 /etc/android-timezone.txt | tr -d ' \r\n')"
fi
if [ -z "$TZ_NAME" ] && [ -f /etc/timezone ]; then
    TZ_NAME="$(head -n1 /etc/timezone | tr -d ' \r\n')"
fi
if [ -n "$TZ_NAME" ] && [ -f "/usr/share/zoneinfo/$TZ_NAME" ]; then
    ln -sfn "/usr/share/zoneinfo/$TZ_NAME" /etc/localtime 2>/dev/null \
        && log "时区：$TZ_NAME" || log "WARN: 设置 /etc/localtime 失败"
    printf '%s\n' "$TZ_NAME" > /etc/timezone 2>/dev/null || true
elif [ -f /usr/share/zoneinfo/UTC ]; then
    ln -sfn /usr/share/zoneinfo/UTC /etc/localtime 2>/dev/null || true
    log "时区：回退 UTC（未取到 Android 时区）"
fi

# ---------------------------------------------------------------------------
# 4) 环境变量：HOME / DSH_HOME / PATH / LANG
# ---------------------------------------------------------------------------
export HOME=/root
export DSH_HOME=/root/.dsh
export PATH="/opt/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"
export TERM="${TERM:-xterm-256color}"

# CA 证书路径：**必须显式指定**。
# Node 官方静态构建自带的 OpenSSL 默认 CA 路径不保证与 Ubuntu 约定一致
# （Ubuntu 的 ca-certificates 把 bundle 放在 /etc/ssl/certs/ca-certificates.crt）。
# 不设这一项时，典型症状是"HTTPS 连不上 / unable to verify the first certificate"，
# 而 curl 却正常 —— 极难排查。所以这里显式钉死，并在缺失时告警。
CERT_BUNDLE=/etc/ssl/certs/ca-certificates.crt
if [ -f "$CERT_BUNDLE" ]; then
    export SSL_CERT_FILE="$CERT_BUNDLE"
else
    log "警告：$CERT_BUNDLE 不存在，HTTPS 可能失败（base 层应随附 CA 证书）"
fi

# 明确置空：禁止任何注入式补丁（architecture.md §3.2）
unset NODE_OPTIONS 2>/dev/null || true

# 密钥环境文件：0600 才加载；内容是 KEY=VALUE（由用户/App 写）
ENV_FILE="$DSH_HOME/env"
if [ -f "$ENV_FILE" ]; then
    PERM="$(stat -c '%a' "$ENV_FILE" 2>/dev/null || echo '')"
    if [ "$PERM" = "600" ]; then
        # set -a：让文件里的赋值自动 export；子 shell 里 source 保证失败不污染
        # shellcheck disable=SC1090
        set -a
        if . "$ENV_FILE"; then
            log "已加载环境文件 $ENV_FILE（0600）"
        else
            log "WARN: 环境文件 $ENV_FILE 解析失败，已跳过（密钥不会进命令行）"
        fi
        set +a
    else
        log "WARN: 忽略 $ENV_FILE —— 权限是 ${PERM:-未知}，必须是 600（避免密钥泄露）"
    fi
else
    log "提示：$ENV_FILE 不存在；如需 API key，请写入该文件并 chmod 600"
fi

# 确保 DSH 家目录存在（用户状态写在可写层）
mkdir -p "$DSH_HOME" 2>/dev/null || true

# ---------------------------------------------------------------------------
# 5) 交给 supervisor（**exec**，让 supervise.sh 成为本子进程的直接替代，
#    这样环境内 ps 只有一层，信号也能直达）
# ---------------------------------------------------------------------------
SUP="$SELF_DIR/supervise.sh"
if [ ! -x "$SUP" ]; then
    if [ -f "$SUP" ]; then chmod 0755 "$SUP" 2>/dev/null || true; fi
fi
if [ ! -f "$SUP" ]; then
    log "ERROR: 找不到 supervisor $SUP"
    exit 1
fi

log "entry.sh 就绪，exec $SUP --port $PORT"
exec "$SUP" --port "$PORT"
